<?php
declare(strict_types=1);

/**
 * Service cards + translations (homepage catalog moved to Services page).
 */

$service_catalog_translations = [
    'en' => [
        'page_title' => 'Our Services - Xander Global Scholars',
        'page_description' => 'Apply for study abroad, scholarships, visas, jobs, credit transfer, and travel with Xander Global Scholars.',
        'services_title' => 'Our Services',
        'services_description' => 'Everything you need to study, work, study loan, credit and move abroad — guided by experts.',
        'card_apply' => 'Apply Now',
        'card_copy' => 'Copy Link',
        'direct_header_title' => 'Service access',
        'direct_header_text' => 'You opened a direct link to one service. View all services below or apply now.',
        'back_to_all' => 'View all services',
        'card1_title' => 'Study & Work Abroad',
        'card1_subtitle' => 'Complete guidance for international education and career opportunities',
        'card1_highlight' => 'University applications',
        'card1_point1' => 'Personalized university and course shortlisting',
        'card1_point2' => 'Expert review of SOPs, LORs, and resumes',
        'card1_point3' => 'Student visa interview coaching',
        'card1_point4' => 'Part-time work and post-study visa guidance',
        'card1_description' => 'Navigate international admissions with expert advice tailored to your academic background and career goals.',
        'card2_title' => 'Scholarships & Loans',
        'card2_subtitle' => 'Financial aid solutions to fund your international education',
        'card2_highlight' => 'Up to 90% scholarships',
        'card2_point1' => 'Merit-based and need-based scholarship matching',
        'card2_point2' => 'Scholarship essay and application support',
        'card2_point3' => 'Fast-track student loan approvals with partner banks',
        'card2_point4' => 'Collateral-free loan guidance for eligible students',
        'card2_description' => 'Find the right mix of scholarships, grants, and loans so your international education stays within reach.',
        'card3_title' => 'I-20 Application',
        'card3_subtitle' => 'Expedited processing for US study permits and SEVIS compliance',
        'card3_highlight' => 'SEVIS compliant processing',
        'card3_point1' => 'Step-by-step SEVIS fee payment assistance',
        'card3_point2' => 'Financial document verification for universities',
        'card3_point3' => 'Coordination with university international offices',
        'card3_point4' => 'Guidance on maintaining F-1 student status',
        'card3_description' => 'Get your Form I-20 processed accurately and on time so you can start your US studies without delays.',
        'card4_title' => 'Credit Transfer',
        'card4_subtitle' => 'Seamless credit evaluation and transfer to partner universities',
        'card4_highlight' => 'Official transcript evaluation',
        'card4_point1' => 'GPA conversion and academic record review',
        'card4_point2' => 'Course-by-course equivalency mapping',
        'card4_point3' => 'Strategies to maximize accepted credit hours',
        'card4_point4' => 'Liaison with partner university registrars',
        'card4_description' => 'Transfer completed coursework toward your degree abroad without losing progress you have already earned.',
        'card5_title' => 'Visa Application',
        'card5_subtitle' => 'Complete visa support for students, work, and travel purposes',
        'card5_highlight' => 'High-approval application support',
        'card5_point1' => 'Checklist-driven document preparation and review',
        'card5_point2' => 'Application forms and embassy appointment booking',
        'card5_point3' => 'Mock visa interviews with personalized feedback',
        'card5_point4' => 'Pre-travel briefing and compliance reminders',
        'card5_description' => 'Expert support from document gathering through your visa interview and departure.',
        'card6_title' => 'Apply for Job',
        'card6_subtitle' => 'International career opportunities across Europe and beyond',
        'card6_highlight' => 'Job placement support',
        'card6_point1' => 'Curated roles matched to your skills and goals',
        'card6_point2' => 'Resume and cover letter for international markets',
        'card6_point3' => 'Interview coaching with HR and hiring managers',
        'card6_point4' => 'Access to employer and recruiter partner network',
        'card6_description' => 'Launch or advance your career abroad with end-to-end support from search to offer.',
        'card7_title' => 'Airticketing Reservation',
        'card7_subtitle' => 'Specialized flight bookings for students and professionals',
        'card7_highlight' => 'Student & academic fares',
        'card7_point1' => 'Discounted student and academic fares where eligible',
        'card7_point2' => 'Group booking rates for cohorts and families',
        'card7_point3' => 'Flexible date changes and ticketing options',
        'card7_point4' => 'Travel insurance and itinerary guidance',
        'card7_description' => 'Book flights on timelines that fit academic calendars, with fares and flexibility built for students.',
    ],
    'fr' => [
        'page_title' => 'Nos Services - Xander Global Scholars',
        'page_description' => 'Étudier, travailler, bourses, visas et voyages avec Xander Global Scholars.',
        'services_title' => 'Nos Services',
        'services_description' => 'Tout ce dont vous avez besoin pour étudier, travailler et déménager à l\'étranger.',
        'card_apply' => 'Postuler maintenant',
        'card_copy' => 'Copier le lien',
        'direct_header_title' => 'Accès direct au service',
        'direct_header_text' => 'Vous avez ouvert un lien direct. Consultez tous les services ci-dessous.',
        'back_to_all' => 'Voir tous les services',
        'card1_title' => 'Étudier & Travailler à l\'Étranger',
        'card1_subtitle' => 'Orientation complète pour l\'éducation internationale et les opportunités de carrière',
        'card1_highlight' => 'Candidatures universitaires',
        'card1_point1' => 'Sélection personnalisée d\'universités et de programmes',
        'card1_point2' => 'Relecture experte des SOP, lettres et CV',
        'card1_point3' => 'Coaching pour l\'entretien de visa étudiant',
        'card1_point4' => 'Conseils travail à temps partiel et visa post-études',
        'card1_description' => 'Parcours d\'admission international avec des conseils adaptés à votre profil et vos objectifs.',
        'card2_title' => 'Bourses & Prêts',
        'card2_subtitle' => 'Solutions d\'aide financière pour financer vos études internationales',
        'card2_highlight' => 'Bourses jusqu\'à 90%',
        'card2_point1' => 'Repérage de bourses au mérite et selon les besoins',
        'card2_point2' => 'Aide aux dossiers et essais de bourse',
        'card2_point3' => 'Prêts étudiants accélérés via nos banques partenaires',
        'card2_point4' => 'Orientation prêts sans garantie pour profils éligibles',
        'card2_description' => 'Trouvez le bon mix de bourses, subventions et prêts pour financer vos études à l\'étranger.',
        'card3_title' => 'Demande I-20',
        'card3_subtitle' => 'Traitement accéléré pour permis d\'étude USA et conformité SEVIS',
        'card3_highlight' => 'Traitement conforme SEVIS',
        'card3_point1' => 'Accompagnement pas à pas pour les frais SEVIS',
        'card3_point2' => 'Vérification des justificatifs financiers',
        'card3_point3' => 'Coordination avec les bureaux internationaux',
        'card3_point4' => 'Conseils pour maintenir le statut F-1',
        'card3_description' => 'Obtenez votre formulaire I-20 correctement et à temps pour commencer vos études aux États-Unis.',
        'card4_title' => 'Transfert de Crédits',
        'card4_subtitle' => 'Évaluation et transfert de crédits vers universités partenaires',
        'card4_highlight' => 'Évaluation officielle des relevés',
        'card4_point1' => 'Conversion de notes et analyse du parcours',
        'card4_point2' => 'Équivalence cours par cours',
        'card4_point3' => 'Stratégies pour maximiser les crédits acceptés',
        'card4_point4' => 'Liaison avec les registrars partenaires',
        'card4_description' => 'Valorisez vos crédits déjà obtenus dans votre parcours à l\'étranger.',
        'card5_title' => 'Demande de Visa',
        'card5_subtitle' => 'Support complet pour visas étudiants, travail et voyage',
        'card5_highlight' => 'Accompagnement dossier à fort taux d\'acceptation',
        'card5_point1' => 'Préparation et contrôle des documents',
        'card5_point2' => 'Formulaires et prise de rendez-vous ambassade',
        'card5_point3' => 'Entretiens blancs avec retours personnalisés',
        'card5_point4' => 'Briefing pré-voyage et rappels de conformité',
        'card5_description' => 'Un accompagnement expert du dossier jusqu\'à l\'entretien et le départ.',
        'card6_title' => 'Postuler à un Emploi',
        'card6_subtitle' => 'Opportunités de carrière internationales en Europe et au-delà',
        'card6_highlight' => 'Support placement emploi',
        'card6_point1' => 'Offres ciblées selon vos compétences',
        'card6_point2' => 'CV et lettre adaptés aux marchés internationaux',
        'card6_point3' => 'Coaching entretien avec recruteurs',
        'card6_point4' => 'Accès au réseau employeurs partenaires',
        'card6_description' => 'Lancez ou développez votre carrière à l\'étranger, de la recherche à l\'offre.',
        'card7_title' => 'Réservation de Billets',
        'card7_subtitle' => 'Réservations de vols spécialisées pour étudiants et professionnels',
        'card7_highlight' => 'Tarifs étudiants & académiques',
        'card7_point1' => 'Tarifs réduits étudiants et académiques',
        'card7_point2' => 'Tarifs groupe pour cohortes et familles',
        'card7_point3' => 'Changements de dates et billets flexibles',
        'card7_point4' => 'Assurance voyage et conseils d\'itinéraire',
        'card7_description' => 'Réservez des vols adaptés au calendrier académique, avec tarifs et flexibilité étudiants.',
    ],
];

$service_catalog_cards = [
    ['id' => 'admissions', 'icon' => '🎓', 'title_key' => 'card1_title', 'subtitle_key' => 'card1_subtitle', 'description_key' => 'card1_description', 'highlight_key' => 'card1_highlight', 'point_keys' => ['card1_point1', 'card1_point2', 'card1_point3', 'card1_point4'], 'form' => 'student-application.php'],
    ['id' => 'scholarships', 'icon' => '💰', 'title_key' => 'card2_title', 'subtitle_key' => 'card2_subtitle', 'description_key' => 'card2_description', 'highlight_key' => 'card2_highlight', 'point_keys' => ['card2_point1', 'card2_point2', 'card2_point3', 'card2_point4'], 'form' => 'master-loan.php'],
    ['id' => 'i20', 'icon' => '📄', 'title_key' => 'card3_title', 'subtitle_key' => 'card3_subtitle', 'description_key' => 'card3_description', 'highlight_key' => 'card3_highlight', 'point_keys' => ['card3_point1', 'card3_point2', 'card3_point3', 'card3_point4'], 'form' => 'form-20.php'],
    ['id' => 'credit', 'icon' => '🔁', 'title_key' => 'card4_title', 'subtitle_key' => 'card4_subtitle', 'description_key' => 'card4_description', 'highlight_key' => 'card4_highlight', 'point_keys' => ['card4_point1', 'card4_point2', 'card4_point3', 'card4_point4'], 'form' => 'credit_transfer.php'],
    ['id' => 'visa', 'icon' => '✈️', 'title_key' => 'card5_title', 'subtitle_key' => 'card5_subtitle', 'description_key' => 'card5_description', 'highlight_key' => 'card5_highlight', 'point_keys' => ['card5_point1', 'card5_point2', 'card5_point3', 'card5_point4'], 'form' => 'visa.php'],
    ['id' => 'jobs', 'icon' => '💼', 'title_key' => 'card6_title', 'subtitle_key' => 'card6_subtitle', 'description_key' => 'card6_description', 'highlight_key' => 'card6_highlight', 'point_keys' => ['card6_point1', 'card6_point2', 'card6_point3', 'card6_point4'], 'form' => 'job-application.php'],
    ['id' => 'airticket', 'icon' => '🛫', 'title_key' => 'card7_title', 'subtitle_key' => 'card7_subtitle', 'description_key' => 'card7_description', 'highlight_key' => 'card7_highlight', 'point_keys' => ['card7_point1', 'card7_point2', 'card7_point3', 'card7_point4'], 'form' => 'air-ticket-reservation.php'],
];

if (!function_exists('st')) {
    function st(string $key): string
    {
        global $service_catalog_translations, $current_lang;
        $lang = $current_lang ?? 'en';

        return $service_catalog_translations[$lang][$key]
            ?? $service_catalog_translations['en'][$key]
            ?? $key;
    }
}

function xander_service_catalog_ids(): array
{
    global $service_catalog_cards;

    return array_column($service_catalog_cards, 'id');
}
